# Generated by Django 4.2.7 on 2023-11-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('about_food', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='img')),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('food_time', models.TimeField(auto_now_add=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('Classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_module.classification_food')),
                ('like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
