# Generated by Django 4.2.7 on 2023-11-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0002_classification_food_food_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('facebook_link', models.URLField()),
                ('x_link', models.URLField()),
                ('linkdin_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('pinterest_link', models.URLField()),
            ],
        ),
    ]
