# Generated by Django 4.2.7 on 2023-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0003_footer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('number_of_guests', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('timee', models.TimeField(null=True)),
            ],
        ),
    ]
