# Generated by Django 4.2.7 on 2023-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0006_alter_food_menu_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('text_area', models.TextField(max_length=800)),
                ('is_aactive', models.BooleanField(default=False)),
            ],
        ),
    ]
