# Generated by Django 4.2.7 on 2023-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_data',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='linkdin_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='pinterest_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='x_link',
            field=models.URLField(null=True),
        ),
    ]
