# Generated by Django 4.2.7 on 2023-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0008_alter_footer_data_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_data',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='linkdin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='pinterest_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer_data',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
