# Generated by Django 4.2.7 on 2023-11-26 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0010_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='w_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
