# Generated by Django 4.2.7 on 2023-11-26 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0012_rename_w_user_reservation_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_menu',
            name='like',
        ),
        migrations.AddField(
            model_name='food_menu',
            name='like_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_part', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food_menu',
            name='user_order',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='discount',
            field=models.IntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
