# Generated by Django 4.1 on 2024-03-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0015_alter_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='is_aactive',
            new_name='is_active_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classification_food',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_module.classification_food'),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='food_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
