# Generated by Django 4.1 on 2024-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0016_rename_is_aactive_comments_is_active_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_menu',
            name='discount',
            field=models.IntegerField(default=234),
            preserve_default=False,
        ),
    ]
