# Generated by Django 4.2.7 on 2023-11-26 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0013_remove_food_menu_like_food_menu_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_menu',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_part', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='user_order',
            field=models.ManyToManyField(blank=True, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
